//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PomaPlayer.SoftArc.Web.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PomaPlayer.SoftArc.Web.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Город.
        /// </summary>
        public static string CenterDto_AddressCity {
            get {
                return ResourceManager.GetString("CenterDto_AddressCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дом.
        /// </summary>
        public static string CenterDto_AddressNumberHouse {
            get {
                return ResourceManager.GetString("CenterDto_AddressNumberHouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Улица.
        /// </summary>
        public static string CenterDto_AddressStreet {
            get {
                return ResourceManager.GetString("CenterDto_AddressStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Идентификатор центра.
        /// </summary>
        public static string CenterDto_IsnNode {
            get {
                return ResourceManager.GetString("CenterDto_IsnNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наименование.
        /// </summary>
        public static string CenterDto_Name {
            get {
                return ResourceManager.GetString("CenterDto_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на День рождения.
        /// </summary>
        public static string CustomerDto_Birthday {
            get {
                return ResourceManager.GetString("CustomerDto_Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Идентификатор центра.
        /// </summary>
        public static string CustomerDto_IsnCenter {
            get {
                return ResourceManager.GetString("CustomerDto_IsnCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Идентификатор клиента.
        /// </summary>
        public static string CustomerDto_IsnNode {
            get {
                return ResourceManager.GetString("CustomerDto_IsnNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отчетство.
        /// </summary>
        public static string CustomerDto_LastName {
            get {
                return ResourceManager.GetString("CustomerDto_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя.
        /// </summary>
        public static string CustomerDto_Name {
            get {
                return ResourceManager.GetString("CustomerDto_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фамилия.
        /// </summary>
        public static string CustomerDto_SurName {
            get {
                return ResourceManager.GetString("CustomerDto_SurName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Город.
        /// </summary>
        public static string EditCenterDto_AddressCity {
            get {
                return ResourceManager.GetString("EditCenterDto_AddressCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дом.
        /// </summary>
        public static string EditCenterDto_AddressNumberHouse {
            get {
                return ResourceManager.GetString("EditCenterDto_AddressNumberHouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Улица.
        /// </summary>
        public static string EditCenterDto_AddressStreet {
            get {
                return ResourceManager.GetString("EditCenterDto_AddressStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Идентификатор центра.
        /// </summary>
        public static string EditCenterDto_IsnNode {
            get {
                return ResourceManager.GetString("EditCenterDto_IsnNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наименование.
        /// </summary>
        public static string EditCenterDto_Name {
            get {
                return ResourceManager.GetString("EditCenterDto_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на День рождения.
        /// </summary>
        public static string EditCustomerDto_Birthday {
            get {
                return ResourceManager.GetString("EditCustomerDto_Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Идентификатор центра.
        /// </summary>
        public static string EditCustomerDto_IsnCenter {
            get {
                return ResourceManager.GetString("EditCustomerDto_IsnCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Идентификатор клиента.
        /// </summary>
        public static string EditCustomerDto_IsnNode {
            get {
                return ResourceManager.GetString("EditCustomerDto_IsnNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отчетство.
        /// </summary>
        public static string EditCustomerDto_LastName {
            get {
                return ResourceManager.GetString("EditCustomerDto_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя.
        /// </summary>
        public static string EditCustomerDto_Name {
            get {
                return ResourceManager.GetString("EditCustomerDto_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фамилия.
        /// </summary>
        public static string EditCustomerDto_SurName {
            get {
                return ResourceManager.GetString("EditCustomerDto_SurName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Идентификатор тренера.
        /// </summary>
        public static string EditTrainerDto_IsnNode {
            get {
                return ResourceManager.GetString("EditTrainerDto_IsnNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отчество.
        /// </summary>
        public static string EditTrainerDto_LastName {
            get {
                return ResourceManager.GetString("EditTrainerDto_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя.
        /// </summary>
        public static string EditTrainerDto_Name {
            get {
                return ResourceManager.GetString("EditTrainerDto_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Специализация.
        /// </summary>
        public static string EditTrainerDto_Specialization {
            get {
                return ResourceManager.GetString("EditTrainerDto_Specialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фамилия.
        /// </summary>
        public static string EditTrainerDto_SurName {
            get {
                return ResourceManager.GetString("EditTrainerDto_SurName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Город.
        /// </summary>
        public static string InfoCenterDto_AddressCity {
            get {
                return ResourceManager.GetString("InfoCenterDto_AddressCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дом.
        /// </summary>
        public static string InfoCenterDto_AddressNumberHouse {
            get {
                return ResourceManager.GetString("InfoCenterDto_AddressNumberHouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Улица.
        /// </summary>
        public static string InfoCenterDto_AddressStreet {
            get {
                return ResourceManager.GetString("InfoCenterDto_AddressStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Клиенты.
        /// </summary>
        public static string InfoCenterDto_Customers {
            get {
                return ResourceManager.GetString("InfoCenterDto_Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Идентификатор центра.
        /// </summary>
        public static string InfoCenterDto_IsnCenter {
            get {
                return ResourceManager.GetString("InfoCenterDto_IsnCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Идентификатор центра.
        /// </summary>
        public static string InfoCenterDto_IsnNode {
            get {
                return ResourceManager.GetString("InfoCenterDto_IsnNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наименование.
        /// </summary>
        public static string InfoCenterDto_Name {
            get {
                return ResourceManager.GetString("InfoCenterDto_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тренеры.
        /// </summary>
        public static string InfoCenterDto_Trainers {
            get {
                return ResourceManager.GetString("InfoCenterDto_Trainers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на День рождения.
        /// </summary>
        public static string InfoCustomerDto_Birthday {
            get {
                return ResourceManager.GetString("InfoCustomerDto_Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Центр.
        /// </summary>
        public static string InfoCustomerDto_Center {
            get {
                return ResourceManager.GetString("InfoCustomerDto_Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Идентификатор клиента.
        /// </summary>
        public static string InfoCustomerDto_IsnNode {
            get {
                return ResourceManager.GetString("InfoCustomerDto_IsnNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отчество.
        /// </summary>
        public static string InfoCustomerDto_LastName {
            get {
                return ResourceManager.GetString("InfoCustomerDto_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя.
        /// </summary>
        public static string InfoCustomerDto_Name {
            get {
                return ResourceManager.GetString("InfoCustomerDto_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фамилия.
        /// </summary>
        public static string InfoCustomerDto_SurName {
            get {
                return ResourceManager.GetString("InfoCustomerDto_SurName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тренеры.
        /// </summary>
        public static string InfoCustomerDto_Trainers {
            get {
                return ResourceManager.GetString("InfoCustomerDto_Trainers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Центры.
        /// </summary>
        public static string InfoTrainerDto_Centers {
            get {
                return ResourceManager.GetString("InfoTrainerDto_Centers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Клиенты.
        /// </summary>
        public static string InfoTrainerDto_Customers {
            get {
                return ResourceManager.GetString("InfoTrainerDto_Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Идентификатор тренера.
        /// </summary>
        public static string InfoTrainerDto_IsnNode {
            get {
                return ResourceManager.GetString("InfoTrainerDto_IsnNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отчество.
        /// </summary>
        public static string InfoTrainerDto_LastName {
            get {
                return ResourceManager.GetString("InfoTrainerDto_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя.
        /// </summary>
        public static string InfoTrainerDto_Name {
            get {
                return ResourceManager.GetString("InfoTrainerDto_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Специализация.
        /// </summary>
        public static string InfoTrainerDto_Specialization {
            get {
                return ResourceManager.GetString("InfoTrainerDto_Specialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фамилия.
        /// </summary>
        public static string InfoTrainerDto_SurName {
            get {
                return ResourceManager.GetString("InfoTrainerDto_SurName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Значение поля &apos;{0}&apos; должно быть не более {1} символов.
        /// </summary>
        public static string MaxLength {
            get {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле &apos;{0}&apos; обязательно для заполнения.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Идентификатор клиента.
        /// </summary>
        public static string SetBindWithCustomerDto_IsnCustomer {
            get {
                return ResourceManager.GetString("SetBindWithCustomerDto_IsnCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Идентификатор тренера.
        /// </summary>
        public static string SetBindWithCustomerDto_IsnTrainer {
            get {
                return ResourceManager.GetString("SetBindWithCustomerDto_IsnTrainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Идентификатор центра.
        /// </summary>
        public static string SetBindWithTrainerDto_IsnCenter {
            get {
                return ResourceManager.GetString("SetBindWithTrainerDto_IsnCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Идентификатор клиента.
        /// </summary>
        public static string SetBindWithTrainerDto_IsnTrainer {
            get {
                return ResourceManager.GetString("SetBindWithTrainerDto_IsnTrainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Идентификатор тренера.
        /// </summary>
        public static string TrainerDto_IsnNode {
            get {
                return ResourceManager.GetString("TrainerDto_IsnNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отчество.
        /// </summary>
        public static string TrainerDto_LastName {
            get {
                return ResourceManager.GetString("TrainerDto_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя.
        /// </summary>
        public static string TrainerDto_Name {
            get {
                return ResourceManager.GetString("TrainerDto_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Специализация.
        /// </summary>
        public static string TrainerDto_Specialization {
            get {
                return ResourceManager.GetString("TrainerDto_Specialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фамилия.
        /// </summary>
        public static string TrainerDto_SurName {
            get {
                return ResourceManager.GetString("TrainerDto_SurName", resourceCulture);
            }
        }
    }
}
